### ISSUE TITLE
Incorrect indentation in code example in mistake 22

### ISSUE THREAD

**Issue by ChristoWolf** [teivah/100-go-mistakes#11]
Unless I am completely overlooking something, the `customer` instantiations in the code example at the bottom of page 73 should not be indented.

**Comment by teivah** [comment]
Ah, I see, indeed... Thanks for spotting it 🙏  It'll be fixed in the next revision.

**Comment by ChristoWolf** [comment]
Thanks, happy to help!
Great book BTW :)
