### ISSUE TITLE
A possible contradicting statement in `#54: Not handling defer errors`

### ISSUE THREAD

**Issue by leelavg** [teivah/100-go-mistakes#25]
- The book is a delightful read, can be put into action easily, so thanks for it.
- Considering below statements

> which we will implement, is to return the rows.Scan error but log the rows.Close error

vs

> so we decide to log "err" and return the existing error.
- shouldn't above be `so we decide to log "closeErr" and return the existing error.`
- first statement seems to be correct, however the code snippet follows second statement
https://github.com/teivah/100-go-mistakes/blob/b2152d01bbe3397f7df3bc8af10a62a6f8e07aa9/07-error-management/54-defer-errors/main.go#L32-L50
- I believe in line 41 it should be `log.Printf("failed to close rows: %v", closeErr)`
- I know it's a small typo, however thought of reporting it due to contradicting statements

Thanks.

**Comment by teivah** [comment]
Thank you very much. I will handle all your remarks in the next release (the repo has been updated).
