### ISSUE TITLE
Probably an incomplete statement in `#61: Propagating an inappropriate context`

### ISSUE THREAD

**Issue by leelavg** [teivah/100-go-mistakes#26]
- First three different conditions are mentioned which can cancel HTTP Request
- An issue was identified with third condition
- It was fixed by providing & explaining a solution, however the fix doesn't seem to satisfy first two conditions
- IOW, if we are using a detached context doesn't publish get executed even though if one of first two conditions are met?
- Probably adding a statement stating the intention it's only to get values might be good 🤔
- Pardon & disregard the issue if my understating is incorrect
``` go
package main

import (
	"context"
	"fmt"
	"time"
)

type detach struct{ ctx context.Context }

func (d detach) Deadline() (time.Time, bool) { return time.Time{}, false }
func (d detach) Done() <-chan struct{}       { return nil }
func (d detach) Err() error                  { return nil }
func (d detach) Value(key any) any           { return d.ctx.Value(key) }

func publish(ctx context.Context) {
	select {
	case <-ctx.Done():
		fmt.Println(ctx.Err())
	case <-time.After(100 * time.Millisecond):
		fmt.Println("published")
	}
}

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(50*time.Millisecond))
	defer cancel()
	ctx = context.WithValue(ctx, "key", "value")
	publish(detach{ctx: ctx}) // prints "published" even if the client timed out
}
```
Thanks.

**Comment by AnhQuanTrl** [comment]
Moreover, with golang 1.21, there has been a way to create a new context from parent context without cancel: [here](https://pkg.go.dev/context#WithoutCancel)

**Comment by teivah** [comment]
You are @leelavg this should have been mentioned for clarity. I'll handle it in the next version, thank you very much.
