### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by JustZyx** [teivah/100-go-mistakes#3]
Gophers in China are also interested in [100-go-mistakes-how-to-avoid-them](https://livebook.manning.com/book/100-go-mistakes-and-how-to-avoid-them/)，but Chinese edition is not available yet.  I wish to get your authorization to translate it into Chinese and publish it on Github for free. Thanks a lot @teivah

**Comment by teivah** [comment]
@JustZyx No, it's a paid book, for sure you won't get the authorization to publish something for free.
Please contact Manning if you need more information.

**Comment by JustZyx** [comment]
> 

Okay, what a pity. Looking forward to be published in China. If need help, I hope to join. Thanks again.

**Comment by teivah** [comment]
You can still ask Manning if you believe there's a need for it 😉

**Comment by teivah** [comment]
@JustZyx FYI, I heard that my e

**Comment by teivah** [comment]
@JustZyx FYI: I heard that Manning has found an agreement with a Chinese publisher to make a Chinese version.
By the way, I know there's a lot of interest from China so if you know someone who would be interested in translating the [README](https://github.com/teivah/100-go-mistakes/blob/master/README.md) in Chinese, please let me know 🙂 I think it could be useful for many people.
