### ISSUE TITLE
spell mistake

### ISSUE THREAD

**Issue by ThomasMing0915** [teivah/100-go-mistakes#4]
hello, i find one spell mistake in 100-go-mistakes at chapter 9 #63 - Not being careful with goroutines and loop variable.

in the code, use fmt.Print :

```golang
s := []int{1, 2, 3}

for _, i := range s {
        go func() {
                fmt.Print(i)
        }()
}
```

in the description, use fmt.Println:

it prints the value of i at the time fmt.Println is executed

**Comment by teivah** [comment]
Ah good one. Thanks @ThomasMing0915, I fixed it.
