### ISSUE TITLE
Potentially mistakenly included tag markers

### ISSUE THREAD

**Issue by aaraney** [teivah/100-go-mistakes#67]
First off, thanks for creating and releasing this content, @teivah! Ive thoroughly enjoyed everything ive read thus far! Can't wait for my hard copy of your book to arrive.

I wasn't sure if these tag like markers (i.e. `<1>`) were mistakenly included or not? I did not see them mentioned in text as if they were reference points, so I thought it was best to ask. Im happy to submit a PR to remove them if that is the case. JLMK.

https://github.com/teivah/100-go-mistakes/blob/668d6165fe7cbb50c9ab839e87c86050c47a0c23/docs/9-generics.md?plain=1#L68-L69

**Comment by teivah** [comment]
Fixed, thanks for letting me know.
