### ISSUE TITLE
Mistake #22 "nil vs empty slices" regarding memory allocation of empty slices

### ISSUE THREAD

**Issue by denpeshkov** [teivah/100-go-mistakes#74]
Item 22 says:
> One of the main differences between a `nil` and an empty slice regards allocations. Initializing a `nil` slice doesn’t require any allocation, which isn’t the case for an empty slice.

Correct me if I am wrong, but AFAIK both slices will have no memory allocations.

Slices are represented in memory as 3 words, defined by the *slice header*:
```go
type slice struct {
	array unsafe.Pointer
	len   int
	cap   int
}
```

A `nil` slice is actually a zero value of the slice header:
```go
slice {
	array: nil,
	len:   0,
	cap:   0,
}
```

An empty slice is just a slice with `len` and `cap` equal to 0 and an `array` pointing to 'zero-sized' array:
```go
slice {
	array: unsafe.Pointer(&zerobase),
	len:   0,
	cap:   0,
}
```
The value of the array is the address of the `runtime.zerobase`, the base address for all 0-byte allocations

**Comment by wureny** [comment]
The empty slice itself doesn't need memory allocation, but when Initializing it, we also need to initialize the slice header, which contains a pointer(array) that needs memory allocations. zerobase is the base address for all 0-byte allocations, but itself is not 0.

**Comment by denpeshkov** [comment]
I am not really proficient in Assembly, but looking at the code, the only difference is which value gets stored in `AX` register.

Assembler for `nil` slice:
```asm
XORL	AX, AX // zeroing
XORL	BX, BX // zeroing
MOVQ	BX, CX	
```

Assembler for empty slice:
```asm
LEAQ	runtime.zerobase(SB), AX // take address
XORL	BX, BX // zeroing
MOVQ	BX, CX
```

Compiled for GOOS=linux GOARCH=AMD64

**Comment by teivah** [comment]
As said in https://github.com/teivah/100-go-mistakes/issues/74#issuecomment-1868293658
