### ISSUE TITLE
Add Fuzz test for #90 

### ISSUE THREAD

**Issue by jeromedoucet** [teivah/100-go-mistakes#9]
**Not considering Fuzz test**

Since go 1.18, this kind of tests may help us to find out missing edge case.

**Solution**

Use it ;) .

**Comment by teivah** [comment]
@jeromedoucet Do you have a specific context in which fuzzing should be applied?

**Comment by jeromedoucet** [comment]
@teivah Yes. At least two :

1 fuzzing is a great help to achieve [a golden master testing strategy](https://en.wikipedia.org/wiki/Characterization_test), when dealing with an untested piece of spaghetti code for instance.

2 Where the code must deals with "external" (and then uncontrolled) input with "complex" checks. It may be a HTTP handler or a database driver or something like that. In such piece of code, the controls over inputs may be critical, and fuzzing may help us to find bugs. 

That's the use case I have for the moment ;)

**Comment by teivah** [comment]
Added, thanks @jeromedoucet 🙏
