### ISSUE TITLE
Correction needed in Data types chapter

### ISSUE THREAD

**Issue by mohammadhsn** [teivah/100-go-mistakes#94]
Thank you for such an incredible book. While reading the fourth season (control structures), I noticed a small mistake. In section 4.2.2 (Arrays), there are three examples demonstrating range loop behavior. The second example is:

```go
a := [3]int{0, 1, 2}
	for i := range a {
		a[2] = 10
		if i == 2 {
			fmt.Printf(a[2])
		}
	}
```
The description says: 

> Because we access the original array, this code prints 2 instead of 10.

However, if you run the code, the number 10 will be shown in the console, which makes sense.

**Comment by ngoctd314** [comment]
original source:
	a := [3]int{0, 1, 2}
	for i, v := range a {
		a[2] = 10
		if i == 2 {
			fmt.Println(v)
		}
	}
a[2] is different with v

**Comment by teivah** [comment]
Thanks, it's part of the typos I was already aware of. I don't think there's anything to be done for the sake of this repo, though.
