### ISSUE TITLE
range iteration has changed

### ISSUE THREAD

**Issue by Kronight** [teivah/100-go-mistakes#96]
**Describe the book error**
go 1.22 range iteration don't share memory，each one malloc memory
Describe a factual error in the book and suggest a correction.

**Comment by teivah** [comment]
@Kronight Isn't this sufficient? 
- https://100go.co/#not-being-careful-with-goroutines-and-loop-variables-63
- https://100go.co/#ignoring-the-impacts-of-using-pointer-elements-in-range-loops-32

Is there anything else you would concretely change?
